/*
S2V Common Constants
UPDATED BY DHAIRYA SHAH
6TH AUG 2019
19/03/2020
*/
public class Commonconstant
{
    public static string futurecall = 'Future Call';
    public static string idlookup= 'Id';
    public static string campaignMember= 'CampaignMember';
    public static string task= 'Task';
    public static string completed= 'Not Started';
    public static String contactmanually = 'Contact Manually';
    public static string inProgress= 'Not Started';
    public static string normal= 'Normal';
    public static string autosubs= 'Automated Airwaves360 Voicemail Sent';
    public static String smstitle ='Automated Airwaves360 SMS Sent'; //'Automated S2VM SMS Sent';
    public static string lead = 'Lead';
    public static string Contact = 'Contact';
    public static string Opportunity = 'Opportunity';
    public static string none = 'None';
    public static string optionSchedule = 'now';  
    public static string status = 'Queue';
    public static String failedStatus = 'Failed';
    public Static boolean stopNotificationcheckbox = false;
    
    
    
}